# syntax=docker/dockerfile:1

FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o server main.go

# Final image
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=builder /app/server /server

CMD ["/server"]
