version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["air"]  # Optional: Hot reloading, needs air binary (see below)
    user: "${MY_UID}:${MY_GID}"